/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pesegato.bigbanana;

import com.google.common.base.CaseFormat;
import com.jme3.app.Application;
import com.jme3.app.SimpleApplication;
import com.jme3.app.state.BaseAppState;
import com.jme3.input.KeyNames;
import com.jme3.input.controls.ActionListener;
import com.jme3.input.controls.KeyTrigger;
import com.jme3.math.Vector3f;
import com.jme3.scene.Node;
import static com.pesegato.bigbanana.BigBananaAppState.defPath;
import com.simsilica.lemur.ActionButton;
import com.simsilica.lemur.CallMethodAction;
import com.simsilica.lemur.Container;
import com.simsilica.lemur.GuiGlobals;
import com.simsilica.lemur.Label;
import java.io.FileOutputStream;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pesegato
 */
public class RemapInputAppState extends BaseAppState {

    private Container mainWindow;

    HashMap<ActionButton, String> mappings = new HashMap<>();
    HashMap<String, ActionButton> mappings2 = new HashMap<>();

    ActionButton selected = null;

    public float getStandardScale() {
        int height = getApplication().getCamera().getHeight();
        return height / 720f;
    }

    @Override
    protected void initialize(Application app) {
        mainWindow = new Container();

        Label title = mainWindow.addChild(new Label("Remap input"));
        title.setFontSize(32);
        addKeyboardButton("keyboard.move.up");
        addKeyboardButton("keyboard.move.down");
        addKeyboardButton("keyboard.move.right");
        addKeyboardButton("keyboard.move.left");
        for (int i = 0; i < BigBananaMapping.getSize(); i++) {
            addKeyboardButton("bigbanana.keyboard." + i);
        }

        // Calculate a standard scale and position from the app's camera
        // height
        int height = app.getCamera().getHeight();
        Vector3f pref = mainWindow.getPreferredSize().clone();

        float standardScale = getStandardScale();
        pref.multLocal(1.5f * standardScale);

        // With a slight bias toward the top
        float y = height * 0.6f + pref.y * 0.5f;

        mainWindow.setLocalTranslation(100 * standardScale, y, 0);
        mainWindow.setLocalScale(1.5f * standardScale);

        for (int i = 0; i < 0xff; i++) {
            getApplication().getInputManager().addMapping(i + "", new KeyTrigger(i));
            getApplication().getInputManager().addListener(al, i + "");
        }
    }

    ActionListener al = new ActionListener() {
        public void onAction(String name, boolean keyPressed, float tpf) {
            if (!keyPressed) {
                if (selected != null) {

                    try {
                        String propKey = BigBananaMapping.getMapping(mappings.get(selected));
                        int keykey = Integer.parseInt(name);
                        String userFriendlyName = KeyNames.getName(keykey);
                        System.out.println(propKey + " / " + keykey + " / " + userFriendlyName);

                        BigBananaAppState.props.setProperty(propKey, userFriendlyName);
                        saveProps();
                        selected.setText(
                                propKey + ": "
                                + //name = "22"
                                //KeyNames.getName(Integer.parseInt(name)) = "Backspace"
                                userFriendlyName
                        //KeyNames.getName(Integer.parseInt(name))
                        //KeyNames.getName(Integer.parseInt(name))
                        );
                        selected = null;
                    } catch (Exception ex) {
                        Logger.getLogger(RemapInputAppState.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    };

    public void saveProps() throws Exception {
        BigBananaAppState.props.store(new FileOutputStream(defPath + "mapping" + ".properties"), "autogenerated");
    }

    private void setSelectedButton(ActionButton ab) {
        if (selected != null) {
            System.out.println("Can't remap two buttons at once!");
            return;
        }
        selected = ab;
        selected.setText(BigBananaMapping.getMapping(mappings.get(ab)) + " ...");
    }

    public void KeyboardMoveUp() {
        setSelectedButton(mappings2.get("keyboard.move.up"));
    }

    public void KeyboardMoveDown() {
        setSelectedButton(mappings2.get("keyboard.move.down"));
    }

    public void KeyboardMoveRight() {
        setSelectedButton(mappings2.get("keyboard.move.right"));
    }

    public void KeyboardMoveLeft() {
        setSelectedButton(mappings2.get("keyboard.move.left"));
    }

    public void BigbananaKeyboard0() {
        setSelectedButton(mappings2.get("bigbanana.keyboard.0"));
    }

    private ActionButton addKeyboardButton(String key) {
        System.out.println(key + "-" + BigBananaMapping.getMapping(key));
        String bbkey = BigBananaMapping.getMapping(key);
        String camelCase = CaseFormat.UPPER_UNDERSCORE.to(CaseFormat.UPPER_CAMEL, key.replace('.', '_'));
        ActionButton action = mainWindow.addChild(new ActionButton(new CallMethodAction(getMapping(bbkey), this, camelCase)));
        mappings.put(action, key);
        mappings2.put(key, action);
        return action;
    }

    private String getMapping(String key) {
        try {
            return key + ": "
                    + BigBananaAppState.props.get(key) //KeyNames.getName(KeyNames.getIndex((String) BigBananaAppState.props.get(key))) //KeyNames.getIndex((String)BigBananaAppState.props.get(key))
                    ;
        } catch (Exception ex) {
            Logger.getLogger(RemapInputAppState.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    @Override
    protected void cleanup(Application app) {
    }

    @Override
    protected void onEnable() {
        Node gui = ((SimpleApplication) getApplication()).getGuiNode();
        gui.attachChild(mainWindow);
        GuiGlobals.getInstance().requestFocus(mainWindow);
    }

    @Override
    protected void onDisable() {
        mainWindow.removeFromParent();
    }

}
